#-*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrantfile for step 2: uses vagrant-hosts for host provisioning
# Variables for puppet configuration:

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  
  config.vm.define :letschat do |node|
    node.vm.box = "hashicorp/precise64"
    node.vm.provision :hosts
    node.vm.network "forwarded_port", guest: 5000, host: 5000
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
end
